### ISSUE TITLE
Is the repo hosted in Maven Central?

### ISSUE THREAD

**Issue by vaibhav3051** [bertramdev/hcl4j#1]
Hey, I was trying to use the parser for variables parsing of terraform scripts but I am unable to find maven dependency for ur repo.

I tried:
- Searching in https://mvnrepository.com/search?q=hcl4j
- creating a project in intellij with gradle framework support but it is also not able to import the dependency

**Comment by kundan13kumar2** [comment]
I am also trying the same as above. can you please help?

**Comment by davydotcom** [comment]
Honestly wasnt expecting that much demand for this right away. I just submitted it for approval on jcenter() should be in mavencentral after that so 24-48 hours. If you want to reference it directly. can reference the bintray url..

https://bintray.com/bertramlabs/gomorpheus/hcl4j

**Comment by davydotcom** [comment]
Now available on maven central

**Comment by kundan13kumar2** [comment]
Thanks for update.
I have string in this HCL format.
appId: 1
transactionId: 1
txnViolationConfig {
  txnKpiType: FALIURE_PERCENTAGE
}

Map<String,Object> mapObject = new HCLParser().parse(string);

And when i m trying to parse this string, I am getting the exception as below:
   
Exception in thread "main" com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <(t) - state: 6> found on line: 4 col: 3
	at com.bertramlabs.plugins.hcl4j.HCLLexer.yylex(HCLLexer.java:993)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:186)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:62)
	at ProtobufConvert.main(ProtobufConvert.java:47)

Thanks, in advance.
