### ISSUE TITLE
Question - parsing to some AST?

### ISSUE THREAD

**Issue by mccartney** [bertramdev/hcl4j#10]
*Question*: @davydotcom do you have any plans for the parsing outcome to be more strongly-typed?
i.e. introduce types for Resources, etc. 

*Context*: I know you can have tons of different resource types and we cannot have object representation hard-coded for any of them. Yet, currently when trying to use the library for parsing my `.tf` files I end up having:
`results.get("resource")` which I need to cast to a `Map<String, String>` and then `.get("the_resource_type_I_know")` and then I get a `Map` instance which makes some sense (resource id -> Map of properties).

**Comment by davydotcom** [comment]
Good point! I'm primarily using it in a groovy app so haven't had that level of complexity in traversing a map. We could totally introduce another parser that is strongly typed

**Comment by davydotcom** [comment]
That being said HCL structure isn't very strongly typed

**Comment by mccartney** [comment]
> That being said HCL structure isn't very strongly typed

Yet there are some types, even visible in your code - arrays, attributes, values, etc. You do recognize if values are boolean/string/number, etc.

I see the point of types not being needed in Groovy.

I am wondering how to contribute on this idea. Do you see some way to keep one parser and have this solved? (so that would require the Groovy usage syntax not to become verbose, yet the types returned being different)

**Comment by ascheman** [comment]
I made a first try wrt option 2.1 (see above). By the language spec the top level object in HCL (2) is a `ConfigurationFile`. Hence, I named the resulting class `HCLConfiguration` and it should contain a list of `HCLAttribute`s and a list of `HCLblock`s.

What do you think?

**Comment by mccartney** [comment]
(I know you weren't asking myself, but... )
I think that's the way to go.

**Comment by ascheman** [comment]
I was asking everyone involved in this ticket / in this project - thanks for your support, @mccartney <3.

**Comment by davydotcom** [comment]
Ok so been a bit busy but getting back to hcl4j and doing a lot of updates. Some of these ideas are not bad but be aware the long term goal was for hcl4j to also perform runtime operations (which it now can do). It is capable of evaluating functions and variable lookups. It is capable of processing boolean conditional expressions, mathematical operations, etc. Currently this is building out as a Map Structure via the processSymbolPass1 and processSymbolPass2. One idea is to have your classes Extend the LinkedHashMap class so its interchangeable for compatibility with additional type casting methods. Another is to indeed make a Typed Parser that can process a similar runtime. I like either of those approaches. The Lexer and Parser should be nearly FULLY hcl2 syntactically complete.
