### ISSUE TITLE
Any API to convert back Map to HCL Terraform Script

### ISSUE THREAD

**Issue by anij** [bertramdev/hcl4j#12]
Hi,

with parse API I have parsed a terraform script and updated 1 resource inside the Map.
Now, how I will again convert back the change in terraform script.

Do hcl4j provide any API for that?
Or any other lib using which I can achieve that

thanks in advance.

**Comment by davydotcom** [comment]
This parser is more intended to act as a runtime parser and build an object graph from the declaritive language of HCL. It is not meant to export back into HCL currently. THis could be done with a different parser in the HCLParser using the same lexxer however. Probably needs coded
