### ISSUE TITLE
I have tried to parse "terraform-aws-vpc" main.tf but it give me below error

### ISSUE THREAD

**Issue by OmalW** [bertramdev/hcl4j#13]
Exception in thread "main" com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <(l) - state: 6> found on line: 3 col: 5

is this because due to "interpolation syntax"?

**Comment by rahulpatil18** [comment]
Can you show us the interpolation code where it's giving the error?

**Comment by davydotcom** [comment]
The parser was significantly upgraded in 0.5.0 including some runtime function behavior. I'd try it out.
