### ISSUE TITLE
variable resolution limitation.md

### ISSUE THREAD

**Issue by srikrishna2001** [bertramdev/hcl4j#14]
**code : **

resource "oci_identity_compartment" "testcompartment1" {
    #Required
    compartment_id = var.compartment_ocid
    description = "demo_compartment"
    name = "demo_compartment1"
}

** coresponding parsemap :**

resource={
                   oci_identity_compartment={
                                                                 testcompartment1={    
                                                                                                    compartment_id=null, 
                                                                                                    description=demo_compartment, 
                                                                                                    name=demo_compartment1
                                                                                                  }
                                                              }
              }

parser is working fine with name,description.
when it comes to variable resolution in (compartment_id = var.compartment_ocid)
 var.compartment_ocid is parsed as either "null" or "com.bertramlabs.plugins.hcl4j.RuntimeSymbols.Variable@56cbfb61"

**issue :**
is there anyway so that i can  get  variable resolution feature included in the parser

**Comment by davydotcom** [comment]
Yes as of 0.5.0 you can now do variable resolution. Simply call `parseVars` before calling the main parse to load a tfVars or call `setVariable(String key, Object value)` or `setVariables(Map)` to set these.
