### ISSUE TITLE
Error processing jsonencode function

### ISSUE THREAD

**Issue by dantolin-iriusrisk** [bertramdev/hcl4j#18]
There is an issue when parsing a file with a resource that uses the Terraform `jsonencode` function. For example:

```
resource "aws_ecs_task_definition" "service" {
  family = "service"
  container_definitions = jsonencode([
    {
      name      = "first"
      image     = "service-first"
      cpu       = 10
      memory    = 512
      essential = true
      portMappings = [
        {
          containerPort = 80
          hostPort      = 80
        }
      ]
    },
    {
      name      = "second"
      image     = "service-second"
      cpu       = 10
      memory    = 256
      essential = true
      portMappings = [
        {
          containerPort = 443
          hostPort      = 443
        }
      ]
    }
  ])

  volume {
    name      = "service-storage"
    host_path = "/ecs/service-storage"
  }

  placement_constraints {
    type       = "memberOf"
    expression = "attribute:ecs.availability-zone in [us-west-2a, us-west-2b]"
  }
}
```

When executing the `HCLParser::parse` function for this example, we got a `HCLParserException` for the line of the `jsonencode`. Is the library supposed to be able to parse this function?

Anyway, if we set the `ignoreParseExceptions` to true, the error is ignored, but the parsing of the file is stopped at the point the exception was raised instead of trying to parse the rest of the document. In this cases, IMO a better behaviour would be to ignore the field where the error appeared and try to get the rest of the components of the HCL file.

**Comment by davydotcom** [comment]
as of 0.5.0 or 0.6.0 this will no longer throw a parse exception. Also 0.6.1 implements the actual behavior of jsonencode when released
