### ISSUE TITLE
Lexing error with dotted attribute names

### ISSUE THREAD

**Issue by jimrthy** [bertramdev/hcl4j#19]
This has the same symptoms as [#13](https://github.com/bertramdev/hcl4j/issues/13). I don't know whether it's the same problem or not.

I've worked a repro case down to

`parser.parse ("module \"foo\" { providers = { bar.baz = quux } }")`

This results in

Execution error (HCLParserException) at com.bertramlabs.plugins.hcl4j.HCLLexer/yylex (HCLLexer.java:1085).
Illegal character <(b) - state: 6> found on line: 1 col: 32

(The spacing may be off. I retyped that from a different machine).

I don't know whether this is related or totally different, or even if this is working as designed. If I take out the dot from the inner attribute name:

`parser.parse ("module \"foo\" { providers = { barbaz = quux } }")`

The resulting hash map has a Null property value for the barbaz key. Maybe because it's a nonsense value with no variable interpretation.

If I make that a string:

`parser.parse ("module \"foo\" { providers = { barbaz = \"quux\" } }")`

it works as I expect.

**Comment by davydotcom** [comment]
I havent seen any examples that use attribute names with . in t hem as a value assignment. Is that anywhere in the HCL specification references from hashi?

**Comment by jimrthy** [comment]
We use them quite a bit in terraform files.

In particular, they show up in provider blocks to modules. One example that I think is generic enough for me to share:

```
providers = {
   aws.dns = aws.dns
   aws = aws.us-east-2
}
```

**Comment by mccartney** [comment]
#38 is related to the last example given

**Comment by davydotcom** [comment]
fixing periods in attribute names done in 0.7.7 based on ID_Continue
