### ISSUE TITLE
Lexing error with object value

### ISSUE THREAD

**Issue by mstine** [bertramdev/hcl4j#27]
Our `.tfvars` files often contain object values like:

```
my_object = {
  object_elem_a: 1,
  object_elem_b: 2
}
```

When I try to parse a file containing one of these with `HCLParser`, I get the following:

```
com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <(o) - state: 6> found on line: 2 col: 3

	at com.bertramlabs.plugins.hcl4j.HCLLexer.yylex(HCLLexer.java:1388)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:307)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:274)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:252)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:217)
```

It appears that this is being interpreted as a block rather than an object value.

**Comment by davydotcom** [comment]
what version of hcl4j are you using?

**Comment by davydotcom** [comment]
confirmed this is functioning fine in 0.6.4 adding test spec with exact content above and it works

**Comment by mstine** [comment]
Thanks for the quick turnaround.

Unfortunately, I just upgraded to 0.6.4, and I'm still getting exactly the same error.

Let me create a minimal reproducer repo.

**Comment by mstine** [comment]
OK - this repo reproduces the issue with the exact content above and 0.6.4: https://github.com/mstine/hcl-object-lexing-issue. It also uses the version of the JVM, Maven, and Kotlin that I'm using in my real project.
