### ISSUE TITLE
slf4j-parent having multiple vulnerabilities

### ISSUE THREAD

**Issue by cglez1987** [bertramdev/hcl4j#39]
Hi guys....first of all I want to thank you for this amazing project. 
Is there any chance to remove slf4j-parent library from dependencies because that library has multiple vulnerabilities and all security scanning tools are RED because of this? Thanks in advance.

https://mvnrepository.com/artifact/org.slf4j/slf4j-parent/1.7.26

**Comment by davydotcom** [comment]
i would not remove it but maybe update it

**Comment by davydotcom** [comment]
updated to 1.7.36 in 0.7.6
