### ISSUE TITLE
HCL v2 support

### ISSUE THREAD

**Issue by ghost** [bertramdev/hcl4j#5]
Hello,

Are you planning to add HCL v2 (terraform 0.12) support?

Thanks!

**Comment by davydotcom** [comment]
Yes

**Comment by christoshadjiaslanis** [comment]
Hi, any updates on this?

**Comment by javydreamercsw** [comment]
Any updates?

**Comment by davydotcom** [comment]
HCLv2 is fully supported check out 0.5.0
