### ISSUE TITLE
Support for Complex types

### ISSUE THREAD

**Issue by aczajkowski** [bertramdev/hcl4j#6]
While defining list and maps with Collection Types e.g.
```
variable "variable_name" {
  type = map(object({
     field1 = string
     field2 = list(string)
  }))
  default = {}
}
```
Failure is raised while parrsing. I know it's 0.12 which is not supported yet here, but would be nice to have a capability to set a lenient mode intenationally to ignore colection types definitions. So error will not be raised at ```(``` when ```type: map(...)``` is defined. And collection type will be skipped.
This will allow us to use collection types and not rollback our current configuration.

**Comment by davydotcom** [comment]
latest version has a new ignoreparse exceptions mode. not sure how far it will get but let me see what i can do here. been working on 0.12 and getting a lot farther.

**Comment by aczajkowski** [comment]
Thank's for hint. We will try to use ignoreparse if this will work for us.

**Comment by akushsky** [comment]
> latest version has a new ignoreparse exceptions mode. not sure how far it will get but let me see what i can do here. been working on 0.12 and getting a lot farther.

Any updates, according to support of complex types?

**Comment by davydotcom** [comment]
Most complex types are supported now. The example above with a nest Ed object() may be the exception. I will look into this

**Comment by akushsky** [comment]
> Most complex types are supported now. The example above with a nest Ed object() may be the exception. I will look into this

I receive type == null for those three cases:

```
variable "cluster_enabled_log_types" {
    description = "A list of the desired control plane logs to enable. For more information, see Amazon EKS Control Plane Logging documentation (https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html)"
    type        = list(string)
    default     = ["audit", "api", "authenticator"]
}

variable "cluster_encryption_config" {
    description = "Configuration block with encryption configuration for the cluster"
    type = list(object({
        provider_key_arn = string
        resources        = list(string)
    }))
    default = []
}

variable "tags" {
    description = "A map of tags to add to all resources"
    type        = map(string)
    default     = {}
}
```

**Comment by akushsky** [comment]
> Most complex types are supported now. The example above with a nest Ed object() may be the exception. I will look into this

Any news or progress?

**Comment by ChristoferDantas** [comment]
I've also noticed that the parser do not work when the variables type are `list(any)` or `map(any)`.

**Comment by davydotcom** [comment]
This has been changed to function correctly except for the (any) attribute. Complex Subtypes should now function in 0.6.0

**Comment by davydotcom** [comment]
list(any) and map(any) should now work in 0.6.1 posting shortly
