### ISSUE TITLE
Update symbol classes to use Long for position, matching JFlex

### ISSUE THREAD

**Issue by rworley-monster** [bertramdev/hcl4j#62]
I'm using Maven and with 0.9.1 I'm getting the same error as in #53.  I tried to build a new jar from `master`, but am getting many compile errors during task compileJava like:
```
build/generated/sources/main/com/bertramlabs/plugins/hcl4j/HCLLexer.java:1894: error: incompatible types: long cannot be converted to Integer
            { currentBlock.appendChild(new StringPrimitiveType(yyline,yycolumn,yychar));
                                                                               ^
```
Are there any special steps needed to compile or is the build simply broken right now?

**Comment by davydotcom** [comment]
It uses gradle wrapper to build . What Java version are you using to perform the build?

**Comment by rworley-monster** [comment]
I'm using openjdk-20.0.2.  I think the problem stems from the [JFlex 1.8.0](https://www.jflex.de/changelog.html#jflex-1.8.0) change "yychar type has been changed from int to long".  I updated the various symbols classes and now it's compiling.  I can submit a PR if you like.

**Comment by davydotcom** [comment]
That would be lovely . I'm betting dependabot did that grrr .

**Comment by rworley-monster** [comment]
Makes you wonder how dependable Dependabot is.  In #46 it wanted to jump two major versions.  That's probably a bit aggressive without full test coverage to identify breaking changes.

**Comment by davydotcom** [comment]
True luckily I have full coverage. Just did those PRs with some other updates pending and planned to do them all at once .
