### ISSUE TITLE
Disable log lines when parsing

### ISSUE THREAD

**Issue by lewisakura** [bertramdev/hcl4j#7]
Hi,

I'm not sure if this is even possible (can't find log lines in any code you've written) but whenever hcl4j parses something it has some log lines like this:

```
[12:50:54 INFO]: Block Element: firstRun - Attribute
[12:50:54 INFO]: Block Element: core - Block
[12:50:54 INFO]: Block Element: core - Block
```

Is there any way these can be disabled?

Cheers.

**Comment by mccartney** [comment]
Looks like the code in `master` no longer has them.

**Comment by mccartney** [comment]
And neither does `0.3.4` which is the latest version I can see.
