### ISSUE TITLE
Advertise latest version

### ISSUE THREAD

**Issue by exaV** [bertramdev/hcl4j#78]
First of all thanks for writing the library, I used version 7.0.0 and it worked like a charm.

Could you include version 9.0.3 of this lib on the Readme? I tried to include version 9.0.1 in my maven project but it failed with an error while downloading dependencies. You can reproduce this with a [simple maven project](https://gist.github.com/torgeir/6742158). The error is no longer present in version 9.0.3 but I did not realize it was released.

FYI the error was introduced with 7.0.1 and present up until 9.0.1:
```
[ERROR] Failed to execute goal on project patrick: Could not resolve dependencies for project com.example:exav:jar:0.0.1-SNAPSHOT
[ERROR] dependency: org.slf4j:slf4j-parent:jar:1.7.36 (compile)
[ERROR] 	Could not find artifact org.slf4j:slf4j-parent:jar:1.7.36 in central (https://repo.maven.apache.org/maven2)

```

Btw in version 9.0.3 I get a ton of logs (without any configuration) on INFO and some "Conditional Matched::" on stdout from [here](https://github.com/bertramdev/hcl4j/blob/d76b5dc3f0a80b082af94d942a2f2c9c22e8819a/src/main/jflex/com/bertramlabs/plugins/hcl4j/HCLLexer.jflex#L533). Can I suggest printing the logs on DEBUG level instead of on INFO at least for most things like "Data Lookup Detected!", because this library is quite useful for scripts (my use-case) where configuring the debug level for a library is a hassle.

There are some errors with files that parsed fine with version 7.0.0 for example I see `Error Parsing HCL...Error Parsing Numerical Value in HCL Attribute` and `Error Processing Tuple from source not a List` (no errors in `terraform validate` or `terraform plan` on my project).

**Comment by davydotcom** [comment]
Regarding logs: yes we can fix that

Regarding your parser errors. 7.0.0 did not interpret tuples and ignored them. This is newer parser functionality. If you can provide samples on the parse errors listed we can get some unit tests in and see why it is occuring.

**Comment by davydotcom** [comment]
Also the read me has been updated for 9.0.4 thank you!
