### ISSUE TITLE
version 0.3.3 unable to parse simple hcl

### ISSUE THREAD

**Issue by zensolution** [bertramdev/hcl4j#8]
After I upgrading to version 0.3.3, I got errors when I am parsing the following,

````
variable "cluster-name" {
  type = string
}
````
The error message is as below. The same input works with 0.2.3.  

com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: com.bertramlabs.plugins.hcl4j.symbols

Thank you for checking this.

**Comment by davydotcom** [comment]
Have you tried on hcl 0.3.4 as it appears to be working for me on that version. Sorry didn't see this issue, it was intended for hcl1 originally and was being ported to hcl2. there's still a few gotyas with 2 but 0.3.4 handles the above better
